insert into songs (Title, Artist, Genre) values ('Melodies of Reflection', 'Logic', 'blues');
insert into songs (Title, Artist, Genre) values ('Celestial Serenade', 'Twenty One Pilots', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Serenade of the Waterfall', 'Shawn Mendes', 'punk');
insert into songs (Title, Artist, Genre) values ('Melodies of the Rainforest', 'Dua Lipa', 'latin');
insert into songs (Title, Artist, Genre) values ('Enchanted Melodies', 'Harry Styles', 'pop');
insert into songs (Title, Artist, Genre) values ('Whispering Dreams', 'Meek Mill', 'latin');
insert into songs (Title, Artist, Genre) values ('Harmony of the Seasons', 'Meghan Trainor', 'alternative');
insert into songs (Title, Artist, Genre) values ('Serenade of the Evening', 'Lizzo', 'rock');
insert into songs (Title, Artist, Genre) values ('Serenade of the Stars', 'One Direction', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Serenade of the Morning', 'Logic', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Celestial Reverie', 'Katy Perry', 'indie');
insert into songs (Title, Artist, Genre) values ('Melodies of the Rainforest', 'Meek Mill', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Celestial Whispers', 'Jason Derulo', 'alternative');
insert into songs (Title, Artist, Genre) values ('Whispers of the Stars', 'Jason Derulo', 'blues');
insert into songs (Title, Artist, Genre) values ('Serenade in the Rain', 'Alessia Cara', 'classical');
insert into songs (Title, Artist, Genre) values ('Serenade of the Sun', 'Justin Timberlake', 'dance');
insert into songs (Title, Artist, Genre) values ('Celestial Whispers', 'Beyonce', 'dance');
insert into songs (Title, Artist, Genre) values ('Serenade of the Fireflies', 'Post Malone', 'rock');
insert into songs (Title, Artist, Genre) values ('Soulful Reverie', 'David Guetta', 'punk');
insert into songs (Title, Artist, Genre) values ('Harmony of the Seasons', 'SZA', 'jazz');
insert into songs (Title, Artist, Genre) values ('Celestial Serenade', 'Wiz Khalifa', 'rock');
insert into songs (Title, Artist, Genre) values ('Whispered Whispers', 'Lizzo', 'classical');
insert into songs (Title, Artist, Genre) values ('Serenade of the Mountains', 'Billie Eilish', 'reggae');
insert into songs (Title, Artist, Genre) values ('Serenade of the Rain', 'Lady Gaga', 'metal');
insert into songs (Title, Artist, Genre) values ('Whispers of the Heart', 'Justin Timberlake', 'r&b');
insert into songs (Title, Artist, Genre) values ('Moonlit Reverie', 'Katy Perry', 'folk');
insert into songs (Title, Artist, Genre) values ('Whispers of the Moon', 'Justin Bieber', 'indie');
insert into songs (Title, Artist, Genre) values ('Starry Night Serenity', 'Ari Lennox', 'alternative');
insert into songs (Title, Artist, Genre) values ('Harmony of the Elements', 'Drake', 'rock');
insert into songs (Title, Artist, Genre) values ('Moonlit Melodies', 'Meek Mill', 'alternative');
insert into songs (Title, Artist, Genre) values ('Whispering Dreams', 'Post Malone', 'jazz');
insert into songs (Title, Artist, Genre) values ('Echoes of Serenity', 'Demi Lovato', 'blues');
insert into songs (Title, Artist, Genre) values ('Harmony of the Night', 'The Chainsmokers', 'classical');
insert into songs (Title, Artist, Genre) values ('Serenade of the Seasons', 'Future', 'country');
insert into songs (Title, Artist, Genre) values ('Serenade of the Desert', 'Calvin Harris', 'folk');
insert into songs (Title, Artist, Genre) values ('Lullaby of the Stars', 'Fifth Harmony', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Whispering Waters', 'Migos', 'latin');
insert into songs (Title, Artist, Genre) values ('Dreams of Tomorrow', 'Demi Lovato', 'indie');
insert into songs (Title, Artist, Genre) values ('Songbird Serenade', 'David Guetta', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Sunset Melodies', 'Coldplay', 'reggae');
insert into songs (Title, Artist, Genre) values ('Starry Night Serenade', 'Katy Perry', 'folk');
insert into songs (Title, Artist, Genre) values ('Whispered Melodies', 'Tyler', 'rock');
insert into songs (Title, Artist, Genre) values ('Melodies of Reflection', 'One Direction', 'alternative');
insert into songs (Title, Artist, Genre) values ('Whispers of the Night', 'Cardi B', 'gospel');
insert into songs (Title, Artist, Genre) values ('Serenade of the Seasons', 'Kanye West', 'soul');
insert into songs (Title, Artist, Genre) values ('Whispers of the Moon', 'Meghan Trainor', 'country');
insert into songs (Title, Artist, Genre) values ('Whispered Whispers', 'Adele', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Melodies of the Past', 'Kendrick Lamar', 'pop');
insert into songs (Title, Artist, Genre) values ('Serenade of the Morning', 'Hailee Steinfeld', 'reggae');
insert into songs (Title, Artist, Genre) values ('Melodies of Eternity', 'Zara Larsson', 'indie');
insert into songs (Title, Artist, Genre) values ('Harmony of the Seasons', 'Avicii', 'punk');
insert into songs (Title, Artist, Genre) values ('Eternal Harmony', 'Cardi B', 'jazz');
insert into songs (Title, Artist, Genre) values ('Melodies of the Cosmos', 'Camila Cabello', 'reggae');
insert into songs (Title, Artist, Genre) values ('Enchanted Melodies', 'Lil Uzi Vert', 'rap');
insert into songs (Title, Artist, Genre) values ('Serenade of the Seasons', 'Twenty One Pilots', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Celestial Dreams', 'Lana Del Rey', 'rap');
insert into songs (Title, Artist, Genre) values ('Dreams of Serenity', 'Taylor Swift', 'reggae');
insert into songs (Title, Artist, Genre) values ('Mystical Journey', 'Tinashe', 'folk');
insert into songs (Title, Artist, Genre) values ('Serenade in the Rain', 'Liam Payne', 'country');
insert into songs (Title, Artist, Genre) values ('Melodies of Serenity', 'Kanye West', 'reggae');
insert into songs (Title, Artist, Genre) values ('Mystical Journey', 'Bruno Mars', 'folk');
insert into songs (Title, Artist, Genre) values ('Whispered Whispers', 'Big Sean', 'soul');
insert into songs (Title, Artist, Genre) values ('Harmony of the Spheres', 'Ricky Martin', 'alternative');
insert into songs (Title, Artist, Genre) values ('Melodies of Tranquility', 'Lizzo', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Melodies of the Rainforest', 'Lorde', 'classical');
insert into songs (Title, Artist, Genre) values ('Serenade of the Morning', 'Childish Gambino', 'dance');
insert into songs (Title, Artist, Genre) values ('Melodies of the Past', 'Lizzo', 'folk');
insert into songs (Title, Artist, Genre) values ('Serenade of the Sun', 'Zedd', 'reggae');
insert into songs (Title, Artist, Genre) values ('Moonlit Sonata', 'P!nk', 'gospel');
insert into songs (Title, Artist, Genre) values ('Summer Breeze', 'Maroon 5', 'r&b');
insert into songs (Title, Artist, Genre) values ('Echoes of the Forest', 'Lauv', 'reggae');
insert into songs (Title, Artist, Genre) values ('Melodies of the Night', 'Zedd', 'metal');
insert into songs (Title, Artist, Genre) values ('Melodies of Bliss', 'Clean Bandit', 'country');
insert into songs (Title, Artist, Genre) values ('Melodies of Tranquility', 'J. Cole', 'latin');
insert into songs (Title, Artist, Genre) values ('Melodies of the Past', 'Ed Sheeran', 'dance');
insert into songs (Title, Artist, Genre) values ('Lullaby of the Stars', 'Meek Mill', 'pop');
insert into songs (Title, Artist, Genre) values ('Serenade of the Evening', 'Halsey', 'rap');
insert into songs (Title, Artist, Genre) values ('Eternal Harmony', 'Gwen Stefani', 'electronic');
insert into songs (Title, Artist, Genre) values ('Lost in the Melody', 'Justin Bieber', 'latin');
insert into songs (Title, Artist, Genre) values ('Lullaby of the Stars', 'Zedd', 'metal');
insert into songs (Title, Artist, Genre) values ('Enchanted Melodies', 'Kygo', 'soul');
insert into songs (Title, Artist, Genre) values ('Enchanted Melodies', 'Tinashe', 'dance');
insert into songs (Title, Artist, Genre) values ('Mystical Journey', 'Camila Cabello', 'pop');
insert into songs (Title, Artist, Genre) values ('Lullaby of the Stars', 'Sia', 'punk');
insert into songs (Title, Artist, Genre) values ('Lullaby of the Stars', 'Shawn Mendes', 'jazz');
insert into songs (Title, Artist, Genre) values ('Whispered Secrets', 'Zayn Malik', 'gospel');
insert into songs (Title, Artist, Genre) values ('Celestial Serenity', 'Alessia Cara', 'r&b');
insert into songs (Title, Artist, Genre) values ('Harmony of the Universe', 'Jay-Z', 'blues');
insert into songs (Title, Artist, Genre) values ('Melodies of Bliss', 'Lizzo', 'classical');
insert into songs (Title, Artist, Genre) values ('Melodies of Wonder', 'Justin Bieber', 'reggae');
insert into songs (Title, Artist, Genre) values ('Celestial Reverie', 'Nick Jonas', 'soul');
insert into songs (Title, Artist, Genre) values ('Moonlit Melodies', 'Dua Lipa', 'indie');
insert into songs (Title, Artist, Genre) values ('Whispering Dreams', 'Kanye West', 'metal');
insert into songs (Title, Artist, Genre) values ('Serenade of the Dawn', 'Travis Scott', 'classical');
insert into songs (Title, Artist, Genre) values ('Whispers of the Heart', 'Rae Sremmurd', 'dance');
insert into songs (Title, Artist, Genre) values ('Melodies of the Heart', 'Shakira', 'country');
insert into songs (Title, Artist, Genre) values ('Whispers in the Wind', 'Shawn Mendes', 'pop');
insert into songs (Title, Artist, Genre) values ('Celestial Serenity', 'Avicii', 'folk');
insert into songs (Title, Artist, Genre) values ('Melodies of the Night', 'P!nk', 'electronic');
insert into songs (Title, Artist, Genre) values ('Whispered Secrets', 'Clean Bandit', 'reggae');
insert into songs (Title, Artist, Genre) values ('Moonlit Melodies', 'Khalid', 'alternative');
insert into songs (Title, Artist, Genre) values ('Moonlit Reverie', 'Harry Styles', 'folk');
insert into songs (Title, Artist, Genre) values ('Enchanted Rhapsody', 'Taylor Swift', 'rap');
insert into songs (Title, Artist, Genre) values ('Melodies of the Night', 'Zedd', 'soul');
insert into songs (Title, Artist, Genre) values ('Songbird Serenade', 'Cardi B', 'punk');
insert into songs (Title, Artist, Genre) values ('Whispered Dreams', 'Future', 'latin');
insert into songs (Title, Artist, Genre) values ('Harmony of the Universe', 'Ariana Grande', 'rap');
insert into songs (Title, Artist, Genre) values ('Harmony of the Universe', 'Logic', 'rap');
insert into songs (Title, Artist, Genre) values ('Whispers of the Night', 'Lil Baby', 'country');
insert into songs (Title, Artist, Genre) values ('Melodies of the Heart', 'Pitbull', 'punk');
insert into songs (Title, Artist, Genre) values ('Whispered Whispers', 'Khalid', 'pop');
insert into songs (Title, Artist, Genre) values ('Melodies of the Past', 'Rihanna', 'rap');
insert into songs (Title, Artist, Genre) values ('Serenade of the Fireflies', 'Demi Lovato', 'dance');
insert into songs (Title, Artist, Genre) values ('Starlit Lullaby', 'The Creator', 'pop');
insert into songs (Title, Artist, Genre) values ('Whispers of the Moon', 'Gucci Mane', 'alternative');
insert into songs (Title, Artist, Genre) values ('Soulful Serenade', 'Migos', 'rock');
insert into songs (Title, Artist, Genre) values ('Dancing in the Moonlight', 'Meghan Trainor', 'blues');
insert into songs (Title, Artist, Genre) values ('Enchanted Melodies', 'Big Sean', 'folk');
insert into songs (Title, Artist, Genre) values ('Melodies of the Cosmos', 'Kesha', 'electronic');
insert into songs (Title, Artist, Genre) values ('Rhythm of the Night', 'Sam Smith', 'metal');
insert into songs (Title, Artist, Genre) values ('Moonlit Reverie', 'Childish Gambino', 'rap');
insert into songs (Title, Artist, Genre) values ('Melodies of the Heart', 'Rita Ora', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Celestial Whispers', 'Gucci Mane', 'alternative');
insert into songs (Title, Artist, Genre) values ('Harmony of the Universe', 'Eminem', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Mystical Journey', 'John Legend', 'jazz');
insert into songs (Title, Artist, Genre) values ('Melodies of the Rainforest', 'Selena Gomez', 'folk');
insert into songs (Title, Artist, Genre) values ('Whispers of the Night', 'Drake', 'indie');
insert into songs (Title, Artist, Genre) values ('Harmony of the Waves', 'Zedd', 'soul');
insert into songs (Title, Artist, Genre) values ('Dancing in the Moonlight', 'Big Sean', 'indie');
insert into songs (Title, Artist, Genre) values ('Celestial Serenade', 'Migos', 'soul');
insert into songs (Title, Artist, Genre) values ('Celestial Whispers', 'Hailee Steinfeld', 'pop');
insert into songs (Title, Artist, Genre) values ('Whispers of the Night', 'Calvin Harris', 'dance');
insert into songs (Title, Artist, Genre) values ('Enchanted Serenity', 'Kanye West', 'classical');
insert into songs (Title, Artist, Genre) values ('Starry Night Whispers', 'Travis Scott', 'dance');
insert into songs (Title, Artist, Genre) values ('Whispering Waters', 'Drake', 'latin');
insert into songs (Title, Artist, Genre) values ('Midnight Melodies', 'David Guetta', 'soul');
insert into songs (Title, Artist, Genre) values ('Celestial Reverie', 'J. Cole', 'indie');
insert into songs (Title, Artist, Genre) values ('Melodies of Reflection', 'David Guetta', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Whispered Dreams', 'Marshmello', 'dance');
insert into songs (Title, Artist, Genre) values ('Melodies of Bliss', 'Bebe Rexha', 'rock');
insert into songs (Title, Artist, Genre) values ('Serenade of the Sun', 'Jonas Brothers', 'latin');
insert into songs (Title, Artist, Genre) values ('Whispered Whispers', 'Lil Wayne', 'metal');
insert into songs (Title, Artist, Genre) values ('Whispering Waters', 'Fergie', 'folk');
insert into songs (Title, Artist, Genre) values ('Serenade of the Ocean', 'Lil Wayne', 'dance');
insert into songs (Title, Artist, Genre) values ('Echoes of Love', 'Fergie', 'reggae');
insert into songs (Title, Artist, Genre) values ('Rhythm of the Night', 'Post Malone', 'folk');
insert into songs (Title, Artist, Genre) values ('Serenade of the Desert', 'Zayn Malik', 'country');
insert into songs (Title, Artist, Genre) values ('Soothing Serenade', 'Taylor Swift', 'rap');
insert into songs (Title, Artist, Genre) values ('Whispers of the Night', 'Shawn Mendes', 'punk');
insert into songs (Title, Artist, Genre) values ('Melodies of Tranquility', 'SZA', 'rock');
insert into songs (Title, Artist, Genre) values ('Eternal Harmony', 'Alessia Cara', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Serenade of the Waterfall', 'Travis Scott', 'classical');
insert into songs (Title, Artist, Genre) values ('Serenade of the Mountains', 'Travis Scott', 'pop');
insert into songs (Title, Artist, Genre) values ('Melodies of the Night', 'Liam Payne', 'pop');
insert into songs (Title, Artist, Genre) values ('Whispered Melodies', 'Lorde', 'classical');
insert into songs (Title, Artist, Genre) values ('Whispers of the Night', 'Jennifer Lopez', 'metal');
insert into songs (Title, Artist, Genre) values ('Starry Night Serenity', 'Drake', 'blues');
insert into songs (Title, Artist, Genre) values ('Serenade of the Soul', 'Future', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Whispered Melodies', 'Zedd', 'folk');
insert into songs (Title, Artist, Genre) values ('Melodies of Wonder', 'Young Thug', 'rock');
insert into songs (Title, Artist, Genre) values ('Whispered Whispers', 'Rae Sremmurd', 'rap');
insert into songs (Title, Artist, Genre) values ('Enchanted Serenity', 'Demi Lovato', 'rap');
insert into songs (Title, Artist, Genre) values ('Songbird Serenade', 'The Chainsmokers', 'latin');
insert into songs (Title, Artist, Genre) values ('Whispers of the Stars', 'Lil Uzi Vert', 'blues');
insert into songs (Title, Artist, Genre) values ('Whispering Waters', 'J. Cole', 'soul');
insert into songs (Title, Artist, Genre) values ('Serenade of the Morning', 'Kendrick Lamar', 'jazz');
insert into songs (Title, Artist, Genre) values ('Harmony of the Universe', 'Charlie XCX', 'alternative');
insert into songs (Title, Artist, Genre) values ('Melodies of the Heart', 'Clean Bandit', 'rock');
insert into songs (Title, Artist, Genre) values ('Celestial Serenade', 'Pitbull', 'country');
insert into songs (Title, Artist, Genre) values ('Echoes of Serenity', 'Meghan Trainor', 'indie');
insert into songs (Title, Artist, Genre) values ('Whispers of the Heart', 'Troye Sivan', 'country');
insert into songs (Title, Artist, Genre) values ('Whispers in the Wind', 'Ellie Goulding', 'reggae');
insert into songs (Title, Artist, Genre) values ('Lullaby of the Moon', 'Alessia Cara', 'alternative');
insert into songs (Title, Artist, Genre) values ('Echoes of the Forest', 'Cardi B', 'country');
insert into songs (Title, Artist, Genre) values ('Lullaby of the Forest', 'Cardi B', 'folk');
insert into songs (Title, Artist, Genre) values ('Harmony of the Universe', 'Kanye West', 'latin');
insert into songs (Title, Artist, Genre) values ('Whispers of the Heart', 'Kesha', 'country');
insert into songs (Title, Artist, Genre) values ('Echoes of Love', 'Ari Lennox', 'classical');
insert into songs (Title, Artist, Genre) values ('Soothing Serenade', 'Gwen Stefani', 'metal');
insert into songs (Title, Artist, Genre) values ('Melodies of the Horizon', 'Gucci Mane', 'electronic');
insert into songs (Title, Artist, Genre) values ('Serenade of the Soul', 'Justin Timberlake', 'soul');
insert into songs (Title, Artist, Genre) values ('Lullaby of the Stars', 'Nick Jonas', 'dance');
insert into songs (Title, Artist, Genre) values ('Enchanted Rhapsody', 'Jay-Z', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Starry Night Serenity', 'Taylor Swift', 'country');
insert into songs (Title, Artist, Genre) values ('Songbird Serenade', 'Sam Smith', 'rock');
insert into songs (Title, Artist, Genre) values ('Whispered Secrets', 'Zedd', 'electronic');
insert into songs (Title, Artist, Genre) values ('Echoes of Love', 'Kesha', 'indie');
insert into songs (Title, Artist, Genre) values ('Echoes of Love', 'Wiz Khalifa', 'latin');
insert into songs (Title, Artist, Genre) values ('Serenade of the Morning', 'The Creator', 'dance');
insert into songs (Title, Artist, Genre) values ('Melodies of Eternity', 'Post Malone', 'indie');
insert into songs (Title, Artist, Genre) values ('Serenade of the Fireflies', 'Eminem', 'classical');
insert into songs (Title, Artist, Genre) values ('Enchanted Rhapsody', 'Wiz Khalifa', 'alternative');
insert into songs (Title, Artist, Genre) values ('Melancholy Memories', 'Lil Uzi Vert', 'soul');
insert into songs (Title, Artist, Genre) values ('Melodies of Serenity', 'Ari Lennox', 'metal');
insert into songs (Title, Artist, Genre) values ('Melodies of Tranquility', 'Halsey', 'r&b');
insert into songs (Title, Artist, Genre) values ('Starlit Lullaby', 'Tyler', 'indie');
insert into songs (Title, Artist, Genre) values ('Serenade of the Waterfall', 'Travis Scott', 'metal');
insert into songs (Title, Artist, Genre) values ('Melodies of Tranquility', 'SZA', 'pop');
insert into songs (Title, Artist, Genre) values ('Moonlit Melodies', 'Justin Bieber', 'rock');
insert into songs (Title, Artist, Genre) values ('Dreams of Serenity', 'Migos', 'soul');
insert into songs (Title, Artist, Genre) values ('Moonlit Reverie', 'Dua Lipa', 'country');
insert into songs (Title, Artist, Genre) values ('Melodies of the Heart', 'Panic! at the Disco', 'gospel');
insert into songs (Title, Artist, Genre) values ('Enchanted Serenity', 'Rita Ora', 'classical');
insert into songs (Title, Artist, Genre) values ('Songbird Serenade', 'Lil Uzi Vert', 'jazz');
insert into songs (Title, Artist, Genre) values ('Soulful Reverie', 'Jennifer Lopez', 'country');
insert into songs (Title, Artist, Genre) values ('Serenade of the Morning', 'P!nk', 'classical');
insert into songs (Title, Artist, Genre) values ('Starry Night Serenity', 'Tori Kelly', 'soul');
insert into songs (Title, Artist, Genre) values ('Serenade of the Sun', 'Logic', 'jazz');
insert into songs (Title, Artist, Genre) values ('Whispered Dreams', 'Kanye West', 'electronic');
insert into songs (Title, Artist, Genre) values ('Serenade of the Waterfall', 'Meghan Trainor', 'indie');
insert into songs (Title, Artist, Genre) values ('Serenade of the Seasons', 'Usher', 'metal');
insert into songs (Title, Artist, Genre) values ('Whispered Whispers', 'Rae Sremmurd', 'reggae');
insert into songs (Title, Artist, Genre) values ('Harmony of the Waves', 'Khalid', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Starry Night Serenade', 'Lady Gaga', 'alternative');
insert into songs (Title, Artist, Genre) values ('Serenade of the Ocean', 'Lil Uzi Vert', 'classical');
insert into songs (Title, Artist, Genre) values ('Melodies of Tranquility', 'Meek Mill', 'indie');
insert into songs (Title, Artist, Genre) values ('Enchanted Melodies', 'Zara Larsson', 'latin');
insert into songs (Title, Artist, Genre) values ('Whispers of the Sea', 'Meek Mill', 'country');
insert into songs (Title, Artist, Genre) values ('Moonlit Reverie', 'Kanye West', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Serenade of the Dawn', 'Shawn Mendes', 'folk');
insert into songs (Title, Artist, Genre) values ('Starry Night Serenade', 'Tyler', 'r&b');
insert into songs (Title, Artist, Genre) values ('Sunset Melodies', 'Cardi B', 'classical');
insert into songs (Title, Artist, Genre) values ('Lullaby of the Forest', 'Kesha', 'gospel');
insert into songs (Title, Artist, Genre) values ('Serenade of the Ocean', 'Kendrick Lamar', 'metal');
insert into songs (Title, Artist, Genre) values ('Whispers of the Wind', 'Lady Gaga', 'pop');
insert into songs (Title, Artist, Genre) values ('Starry Night Whispers', 'Cardi B', 'folk');
insert into songs (Title, Artist, Genre) values ('Echoes of the Forest', 'Future', 'metal');
insert into songs (Title, Artist, Genre) values ('Echoes of the Forest', 'Jennifer Lopez', 'punk');
insert into songs (Title, Artist, Genre) values ('Dreams of Serenity', 'Sam Smith', 'reggae');
insert into songs (Title, Artist, Genre) values ('Melodies of the Night', 'Zedd', 'punk');
insert into songs (Title, Artist, Genre) values ('Lullaby of the Moon', 'Gucci Mane', 'pop');
insert into songs (Title, Artist, Genre) values ('Harmony of the Night', 'The Weeknd', 'blues');
insert into songs (Title, Artist, Genre) values ('Whispering Echoes', 'J. Cole', 'dance');
insert into songs (Title, Artist, Genre) values ('Whispering Wind', 'Ari Lennox', 'jazz');
insert into songs (Title, Artist, Genre) values ('Soothing Serenade', 'Charlie Puth', 'electronic');
insert into songs (Title, Artist, Genre) values ('Enchanted Melodies', 'The Creator', 'latin');
insert into songs (Title, Artist, Genre) values ('Whispers of the Heart', 'Tyler', 'folk');
insert into songs (Title, Artist, Genre) values ('Summer Breeze', 'Wiz Khalifa', 'blues');
insert into songs (Title, Artist, Genre) values ('Lullaby of the Stars', 'Lady Gaga', 'r&b');
insert into songs (Title, Artist, Genre) values ('Melodies of the Horizon', 'Sia', 'classical');
insert into songs (Title, Artist, Genre) values ('Melodies of the Wilderness', 'Gucci Mane', 'electronic');
insert into songs (Title, Artist, Genre) values ('Soulful Serenade', 'Avicii', 'alternative');
insert into songs (Title, Artist, Genre) values ('Melancholy Memories', 'Shakira', 'metal');
insert into songs (Title, Artist, Genre) values ('Midnight Melodies', 'Selena Gomez', 'punk');
insert into songs (Title, Artist, Genre) values ('Serenade of the Desert', 'Miley Cyrus', 'latin');
insert into songs (Title, Artist, Genre) values ('Melodies of Reflection', 'Christina Aguilera', 'pop');
insert into songs (Title, Artist, Genre) values ('Serenade of the Morning', 'Lil Wayne', 'folk');
insert into songs (Title, Artist, Genre) values ('Soulful Reverie', 'Jay-Z', 'folk');
insert into songs (Title, Artist, Genre) values ('Whispers of the Heart', 'Zayn Malik', 'country');
insert into songs (Title, Artist, Genre) values ('Melancholy Memories', 'Charlie XCX', 'alternative');
